---
language: python
services: docker

env:
  global:
    - ROLE_NAME: mergerfs
  matrix:
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: debian8
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: fedora27
    - MOLECULE_DISTRO: fedora29
    - MOLECULE_DISTRO: ubuntu1404
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1804

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  # Run tests.
  - molecule test
