---
- name: Prepare
  hosts: all
  become: true

  pre_tasks:
    - name: PREPARE | Update apt cache on Debian-based distros
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  tasks:
    - name: PREPARE | Simulate partitions
      file:
        path: "/mnt/disk{{ item }}"
        state: directory
      with_sequence: start=1 end=4

    - name: PREPARE | Simulate files on partitions
      copy:
        dest: "/mnt/disk{{ item }}/file-{{ item }}"
        content: "# This is the content of file-{{ item }} on disk{{ item }}"
      with_sequence: start=1 end=4
